/**
 * US states + city suggestions for participant evaluation location fields.
 * Cities are a non-exhaustive list of common metros; users can type any city.
 */

export const US_STATE_OPTIONS: ReadonlyArray<{ readonly code: string; readonly name: string }> = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
];

/** Major / common cities by state for datalist filtering (not exhaustive). */
const SEMINAR_CITIES_BY_STATE: Readonly<Record<string, readonly string[]>> = {
  AL: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa'],
  AK: ['Anchorage', 'Fairbanks', 'Juneau'],
  AZ: ['Chandler', 'Gilbert', 'Glendale', 'Mesa', 'Phoenix', 'Scottsdale', 'Tucson'],
  AR: ['Fayetteville', 'Fort Smith', 'Little Rock', 'Rogers'],
  CA: [
    'Fresno',
    'Long Beach',
    'Los Angeles',
    'Oakland',
    'Sacramento',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Anaheim',
    'Irvine',
    'Riverside',
    'Stockton',
  ],
  CO: ['Aurora', 'Colorado Springs', 'Denver', 'Fort Collins', 'Lakewood'],
  CT: ['Bridgeport', 'Hartford', 'New Haven', 'Stamford', 'Waterbury'],
  DE: ['Dover', 'Wilmington'],
  DC: ['Washington'],
  FL: [
    'Jacksonville',
    'Miami',
    'Orlando',
    'St. Petersburg',
    'Tampa',
    'Fort Lauderdale',
    'Tallahassee',
    'West Palm Beach',
  ],
  GA: ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  HI: ['Honolulu', 'Hilo', 'Kailua'],
  ID: ['Boise', 'Idaho Falls', 'Meridian', 'Nampa'],
  IL: ['Aurora', 'Chicago', 'Joliet', 'Naperville', 'Rockford', 'Springfield'],
  IN: ['Evansville', 'Fort Wayne', 'Indianapolis', 'South Bend'],
  IA: ['Cedar Rapids', 'Davenport', 'Des Moines', 'Sioux City'],
  KS: ['Kansas City', 'Overland Park', 'Topeka', 'Wichita'],
  KY: ['Lexington', 'Louisville', 'Bowling Green'],
  LA: ['Baton Rouge', 'Lafayette', 'New Orleans', 'Shreveport'],
  ME: ['Bangor', 'Portland'],
  MD: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring'],
  MA: ['Boston', 'Cambridge', 'Lowell', 'Springfield', 'Worcester'],
  MI: ['Ann Arbor', 'Detroit', 'Grand Rapids', 'Lansing', 'Sterling Heights'],
  MN: ['Minneapolis', 'Rochester', 'Saint Paul', 'Duluth'],
  MS: ['Biloxi', 'Gulfport', 'Jackson'],
  MO: ['Columbia', 'Independence', 'Kansas City', 'Springfield', 'St. Louis'],
  MT: ['Billings', 'Bozeman', 'Great Falls', 'Missoula'],
  NE: ['Lincoln', 'Omaha'],
  NV: ['Henderson', 'Las Vegas', 'Reno'],
  NH: ['Concord', 'Manchester', 'Nashua'],
  NJ: ['Elizabeth', 'Jersey City', 'Newark', 'Paterson', 'Trenton'],
  NM: ['Albuquerque', 'Las Cruces', 'Santa Fe'],
  NY: ['Albany', 'Buffalo', 'New York', 'Rochester', 'Syracuse', 'Yonkers'],
  NC: ['Charlotte', 'Durham', 'Greensboro', 'Raleigh', 'Winston-Salem'],
  ND: ['Bismarck', 'Fargo', 'Grand Forks'],
  OH: ['Akron', 'Cincinnati', 'Cleveland', 'Columbus', 'Dayton', 'Toledo'],
  OK: ['Norman', 'Oklahoma City', 'Tulsa'],
  OR: ['Eugene', 'Gresham', 'Portland', 'Salem'],
  PA: ['Allentown', 'Erie', 'Philadelphia', 'Pittsburgh', 'Reading'],
  RI: ['Providence', 'Warwick'],
  SC: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach'],
  SD: ['Rapid City', 'Sioux Falls'],
  TN: ['Chattanooga', 'Knoxville', 'Memphis', 'Nashville'],
  TX: [
    'Arlington',
    'Austin',
    'Corpus Christi',
    'Dallas',
    'El Paso',
    'Fort Worth',
    'Houston',
    'Plano',
    'San Antonio',
    'Irving',
    'Lubbock',
  ],
  UT: ['Ogden', 'Provo', 'Salt Lake City', 'West Valley City'],
  VT: ['Burlington', 'Montpelier', 'Rutland'],
  VA: ['Alexandria', 'Chesapeake', 'Norfolk', 'Richmond', 'Virginia Beach'],
  WA: ['Bellevue', 'Seattle', 'Spokane', 'Tacoma', 'Vancouver'],
  WV: ['Charleston', 'Huntington', 'Morgantown'],
  WI: ['Green Bay', 'Madison', 'Milwaukee'],
  WY: ['Casper', 'Cheyenne', 'Laramie'],
};

/**
 * City name suggestions for the selected state, filtered by what the user has typed.
 */
export function filterSeminarCities(stateCode: string, cityQuery: string): string[] {
  const st = stateCode.trim().toUpperCase();
  const cities = SEMINAR_CITIES_BY_STATE[st] ?? [];
  const q = cityQuery.trim().toLowerCase();
  if (!q) return [...cities];
  return cities.filter((c) => c.toLowerCase().includes(q));
}
